# Generated by Django 4.2.6 on 2023-11-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="label",
            old_name="account_id",
            new_name="account",
        ),
    ]
